[tool.black]
line-length = 99
target-version = ['py36']
skip-string-normalization = true

# We need to force-exclude the negated include pattern
# so that pre-commit run --all-files does the correct thing
# see https://github.com/psf/black/issues/1778
force-exclude = '^(?!(main|/(components|bot|tests)/)).*\.py$'
include = '(main|(components|bot|tests)/.*)\.py$'