name: GitHub Pages
on:
  push:
    branches:
      - pages # For testing
      - master

jobs:
  gh-pages:
    name: deploy docs
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        python-version: [3.7]
        os: [ubuntu-latest]
      fail-fast: False
    steps:
      - uses: actions/checkout@v1
      - name: Initialize submodules
        run:
          git submodule update --init --recursive
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -W ignore -m pip install --upgrade pip
          python -W ignore -m pip install -r requirements.txt
          python -W ignore -m pip install -r requirements-dev.txt
          python -W ignore -m pip install -r docs/requirements-docs.txt
      - name: Deploy to GitHub Pages
        run: |
          docs/deploy-gh-pages.sh
        env:
          GH_NAME: ${{ secrets.GH_NAME }}
          GH_EMAIL: ${{ secrets.GH_EMAIL }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        shell: bash
